#ifndef CHARGELAB_OPEN_FIRMWARE_ISO_15118_EV_CERTIFICATE_STATUS_ENUM_TYPE_H
#define CHARGELAB_OPEN_FIRMWARE_ISO_15118_EV_CERTIFICATE_STATUS_ENUM_TYPE_H

#include "openocpp/helpers/json.h"

namespace chargelab::ocpp2_0 {
    CHARGELAB_JSON_ENUM(Iso15118EVCertificateStatusEnumType, 
        Accepted,
        Failed
    )
}

#endif //CHARGELAB_OPEN_FIRMWARE_ISO_15118_EV_CERTIFICATE_STATUS_ENUM_TYPE_H
