#ifndef OPENOCPP_VERSION_H
#define OPENOCPP_VERSION_H

#include "openocpp/common/macro.h"

#define OPENOCPP_VERSION_MAJOR 1
#define OPENOCPP_VERSION_MINOR 0
#define OPENOCPP_VERSION_PATCH 0
#define OPENOCPP_VERSION_TEXT "v" CHARGELAB_XSTR(OPENOCPP_VERSION_MAJOR) "." CHARGELAB_XSTR(OPENOCPP_VERSION_MINOR) "." CHARGELAB_XSTR(OPENOCPP_VERSION_PATCH)

#endif //OPENOCPP_VERSION_H
